### ISSUE TITLE
Need a legacy libs package

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/ffmpeg-os2#3]
Before updating ffmpeg-libs to 4.2.2-1.0c00 this site, https://midimusic.github.io/browsertest/index.html played MP3's fine using Firefox 45.x, after updating, playing fails. You can test in reverse order as the ffmpeg-libs package downgrades easily.
The problem is that Firefox (and SeaMonkey) dynamically loads the FFmpeg libs, libavcodec53-55,57 or after dmik fixed it for OS/2 avcode-53-55,57 and it appears the new lib is avcode-58.dll. Likewise with the corresponding libavutil. As the DLLs are dynamically loaded the only symptoms are certain multimedia sites no longer working or falling back to a supported codec such as opus or vp9.

**Comment by dryeo** [comment]
Meant avcode58.dll above. Edit seems broken.

**Comment by SilvanScherrer** [comment]
The next ffmpeg will have it. But mind you ffox user need to install it by hand. As all ffox rpm dont trigger the automated Installation. Eventually worth a readme change or such.

**Comment by dryeo** [comment]
OK, thanks.

**Comment by dmik** [comment]
Just as a side note, this is by design — FF loads these DLLs dynamically due to copyright issues. Therefore no strict dependency. It has always been like that with FF on Linux systems.

**Comment by dspiatkowski** [comment]
@dmik That makese sense (or rather explains why we had various users on OS2World forum reporting slightly different useage of the DLL), thank you for re-iterating this. I seem to recall that we had this discussion during the original FF45 porting efforts & testing activities too...I think...

**Comment by SilvanScherrer** [comment]
This is done in latest rpm.
